Logged on: 10/01/2016 6:44:51 PM
Exception of type 'DbUpdateConcurrencyException' has been caught.
Message: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.
********************* Stack Trace **********************
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at RAMS.Data.DataContext.Commit() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Data\DataContext.cs:line 54
   at RAMS.Data.Infrastructure.UnitOfWork.Commit() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Data\Infrastructure\UnitOfWork.cs:line 41
   at RAMS.Service.Interfaces.DepartmentService.SaveChanges() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Service\DepartmentService.cs:line 112
   at RAMS.Web.Controllers.WebAPI.DepartmentController.PutDepartment(Department department) in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Web\Controllers\WebAPI\DepartmentController.cs:line 119
****************** End of Stack Trace ******************
******************* Inner Exception ********************
Exception of type 'OptimisticConcurrencyException' has been caught.
Message: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.
********************* Stack Trace **********************
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.ValidateRowsAffected(Int64 rowsAffected, UpdateCommand source)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
****************** End of Stack Trace ******************
**************** End of Inner Exception ****************


Logged on: 10/01/2016 6:45:22 PM
Exception of type 'DepartmentUpdateException' has been caught.
Message: Department could not be updated. Status Code: Conflict
********************* Stack Trace **********************
   at RAMS.Web.Areas.SystemAdmin.Controllers.DepartmentController.<EditDepartment>d__17.MoveNext() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Web\Areas\SystemAdmin\Controllers\DepartmentController.cs:line 174
****************** End of Stack Trace ******************


Logged on: 10/01/2016 6:55:23 PM
Exception of type 'EmployeeUpdateException' has been caught.
Message: Employee profile could not be updated. Status Code: InternalServerError
********************* Stack Trace **********************
   at RAMS.Web.Areas.SystemAdmin.Controllers.UserController.<EditAgent>d__60.MoveNext() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Web\Areas\SystemAdmin\Controllers\UserController.cs:line 1451
****************** End of Stack Trace ******************


Logged on: 10/01/2016 6:55:51 PM
Exception of type 'EmployeeUpdateException' has been caught.
Message: Employee profile could not be updated. Status Code: InternalServerError
********************* Stack Trace **********************
   at RAMS.Web.Areas.SystemAdmin.Controllers.UserController.<EditAgent>d__60.MoveNext() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Web\Areas\SystemAdmin\Controllers\UserController.cs:line 1451
****************** End of Stack Trace ******************


Logged on: 10/01/2016 6:56:03 PM
Exception of type 'EmployeeUpdateException' has been caught.
Message: Employee profile could not be updated. Status Code: InternalServerError
********************* Stack Trace **********************
   at RAMS.Web.Areas.SystemAdmin.Controllers.UserController.<EditAgent>d__60.MoveNext() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Web\Areas\SystemAdmin\Controllers\UserController.cs:line 1451
****************** End of Stack Trace ******************


Logged on: 10/01/2016 6:56:34 PM
Exception of type 'EmployeeUpdateException' has been caught.
Message: Employee profile could not be updated. Status Code: InternalServerError
********************* Stack Trace **********************
   at RAMS.Web.Areas.SystemAdmin.Controllers.UserController.<EditAgent>d__60.MoveNext() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Web\Areas\SystemAdmin\Controllers\UserController.cs:line 1451
****************** End of Stack Trace ******************


Logged on: 10/01/2016 6:58:11 PM
Exception of type 'EmployeeUpdateException' has been caught.
Message: Employee profile could not be updated. Status Code: InternalServerError
********************* Stack Trace **********************
   at RAMS.Web.Areas.SystemAdmin.Controllers.UserController.<EditClient>d__6b.MoveNext() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Web\Areas\SystemAdmin\Controllers\UserController.cs:line 1691
****************** End of Stack Trace ******************


Logged on: 22/01/2016 12:38:49 PM
Exception of type 'DbUpdateException' has been caught.
Message: An error occurred while updating the entries. See the inner exception for details.
********************* Stack Trace **********************
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at RAMS.Data.DataContext.Commit() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Data\DataContext.cs:line 60
   at RAMS.Data.Infrastructure.UnitOfWork.Commit() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Data\Infrastructure\UnitOfWork.cs:line 47
   at RAMS.Service.PositionService.SaveChanges() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Service\PositionService.cs:line 297
   at RAMS.Web.Controllers.WebAPI.PositionController.PostPosition(Position position) in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Web\Controllers\WebAPI\PositionController.cs:line 108
****************** End of Stack Trace ******************
******************* Inner Exception ********************
Exception of type 'UpdateException' has been caught.
Message: An error occurred while updating the entries. See the inner exception for details.
********************* Stack Trace **********************
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
****************** End of Stack Trace ******************
******************* Inner Exception ********************
Exception of type 'SqlException' has been caught.
Message: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_dbo.Positions_dbo.Clients_CleintId". The conflict occurred in database "RAMSData", table "dbo.Clients", column 'ClientId'.
The statement has been terminated.
********************* Stack Trace **********************
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
****************** End of Stack Trace ******************
**************** End of Inner Exception ****************
**************** End of Inner Exception ****************


Logged on: 22/01/2016 12:39:36 PM
Exception of type 'DbUpdateException' has been caught.
Message: An error occurred while updating the entries. See the inner exception for details.
********************* Stack Trace **********************
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at RAMS.Data.DataContext.Commit() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Data\DataContext.cs:line 60
   at RAMS.Data.Infrastructure.UnitOfWork.Commit() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Data\Infrastructure\UnitOfWork.cs:line 47
   at RAMS.Service.PositionService.SaveChanges() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Service\PositionService.cs:line 297
   at RAMS.Web.Controllers.WebAPI.PositionController.PostPosition(Position position) in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Web\Controllers\WebAPI\PositionController.cs:line 108
****************** End of Stack Trace ******************
******************* Inner Exception ********************
Exception of type 'UpdateException' has been caught.
Message: An error occurred while updating the entries. See the inner exception for details.
********************* Stack Trace **********************
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
****************** End of Stack Trace ******************
******************* Inner Exception ********************
Exception of type 'SqlException' has been caught.
Message: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_dbo.Positions_dbo.Clients_CleintId". The conflict occurred in database "RAMSData", table "dbo.Clients", column 'ClientId'.
The statement has been terminated.
********************* Stack Trace **********************
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
****************** End of Stack Trace ******************
**************** End of Inner Exception ****************
**************** End of Inner Exception ****************


Logged on: 22/01/2016 12:43:09 PM
Exception of type 'DbUpdateException' has been caught.
Message: An error occurred while updating the entries. See the inner exception for details.
********************* Stack Trace **********************
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at RAMS.Data.DataContext.Commit() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Data\DataContext.cs:line 60
   at RAMS.Data.Infrastructure.UnitOfWork.Commit() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Data\Infrastructure\UnitOfWork.cs:line 47
   at RAMS.Service.PositionService.SaveChanges() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Service\PositionService.cs:line 297
   at RAMS.Web.Controllers.WebAPI.PositionController.PostPosition(Position position) in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Web\Controllers\WebAPI\PositionController.cs:line 108
****************** End of Stack Trace ******************
******************* Inner Exception ********************
Exception of type 'UpdateException' has been caught.
Message: An error occurred while updating the entries. See the inner exception for details.
********************* Stack Trace **********************
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
****************** End of Stack Trace ******************
******************* Inner Exception ********************
Exception of type 'SqlException' has been caught.
Message: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_dbo.Positions_dbo.Clients_CleintId". The conflict occurred in database "RAMSData", table "dbo.Clients", column 'ClientId'.
The statement has been terminated.
********************* Stack Trace **********************
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
****************** End of Stack Trace ******************
**************** End of Inner Exception ****************
**************** End of Inner Exception ****************


Logged on: 22/01/2016 3:02:12 PM
System.Data.Entity.Validation.DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at RAMS.Data.DataContext.Commit() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Data\DataContext.cs:line 48
Property: Qualifications Error: The Qualifications field is required.


Logged on: 22/01/2016 3:23:55 PM
System.Data.Entity.Validation.DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at RAMS.Data.DataContext.Commit() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Data\DataContext.cs:line 48
Property: Qualifications Error: The Qualifications field is required.


Logged on: 22/01/2016 4:16:21 PM
System.Data.Entity.Validation.DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at RAMS.Data.DataContext.Commit() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Data\DataContext.cs:line 48
Property: Qualifications Error: The Qualifications field is required.


Logged on: 22/01/2016 4:16:59 PM
System.Data.Entity.Validation.DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at RAMS.Data.DataContext.Commit() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Data\DataContext.cs:line 48
Property: Qualifications Error: The Qualifications field is required.


Logged on: 22/01/2016 4:18:16 PM
System.Data.Entity.Validation.DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at RAMS.Data.DataContext.Commit() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Data\DataContext.cs:line 48
Property: Qualifications Error: The Qualifications field is required.


Logged on: 22/01/2016 5:58:31 PM
Exception of type 'DbUpdateException' has been caught.
Message: An error occurred while updating the entries. See the inner exception for details.
********************* Stack Trace **********************
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at RAMS.Data.DataContext.Commit() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Data\DataContext.cs:line 60
   at RAMS.Data.Infrastructure.UnitOfWork.Commit() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Data\Infrastructure\UnitOfWork.cs:line 47
   at RAMS.Service.PositionService.SaveChanges() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Service\PositionService.cs:line 297
   at RAMS.Web.Controllers.WebAPI.PositionController.PostPosition(Position position) in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Web\Controllers\WebAPI\PositionController.cs:line 108
****************** End of Stack Trace ******************
******************* Inner Exception ********************
Exception of type 'UpdateException' has been caught.
Message: An error occurred while updating the entries. See the inner exception for details.
********************* Stack Trace **********************
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
****************** End of Stack Trace ******************
******************* Inner Exception ********************
Exception of type 'SqlException' has been caught.
Message: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_dbo.Positions_dbo.Departments_DepartmentId". The conflict occurred in database "RAMSData", table "dbo.Departments", column 'DepartmentId'.
The statement has been terminated.
********************* Stack Trace **********************
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
****************** End of Stack Trace ******************
**************** End of Inner Exception ****************
**************** End of Inner Exception ****************


Logged on: 22/01/2016 6:00:01 PM
Exception of type 'DbUpdateException' has been caught.
Message: An error occurred while updating the entries. See the inner exception for details.
********************* Stack Trace **********************
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at RAMS.Data.DataContext.Commit() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Data\DataContext.cs:line 60
   at RAMS.Data.Infrastructure.UnitOfWork.Commit() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Data\Infrastructure\UnitOfWork.cs:line 47
   at RAMS.Service.PositionService.SaveChanges() in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Service\PositionService.cs:line 297
   at RAMS.Web.Controllers.WebAPI.PositionController.PostPosition(Position position) in c:\Users\at0mic\Documents\GitHub\RAMS\RAMS.Web\Controllers\WebAPI\PositionController.cs:line 108
****************** End of Stack Trace ******************
******************* Inner Exception ********************
Exception of type 'UpdateException' has been caught.
Message: An error occurred while updating the entries. See the inner exception for details.
********************* Stack Trace **********************
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
****************** End of Stack Trace ******************
******************* Inner Exception ********************
Exception of type 'SqlException' has been caught.
Message: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_dbo.Positions_dbo.Departments_DepartmentId". The conflict occurred in database "RAMSData", table "dbo.Departments", column 'DepartmentId'.
The statement has been terminated.
********************* Stack Trace **********************
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
****************** End of Stack Trace ******************
**************** End of Inner Exception ****************
**************** End of Inner Exception ****************


